services:
  postgres:
    container_name: postgres-smart-accounting
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: smart-accounting-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - smart-accounting-network
    restart: unless-stopped

  smart-accounting-api:
    container_name: smart-accounting-api
    image: smart-accounting/smart-accounting:1.0.3
    ports:
      - "8080:8080"
    networks:
      - smart-accounting-network
    depends_on:
      - postgres

#  wind-recruitment-ui:
#    container_name: wind-recruitment-ui
#    image: #todo : generate the ui image and specify it here
#    ports:
#      - 8080:80
#    networks:
#      - wind-recruitment-network
#    depends_on:
#      - wind-recruitment-api

networks:
  smart-accounting-network:
    driver: bridge

volumes:
  postgres:
    driver: local